### PR TITLE
first version of using new api

### PR DESCRIPTION
**Pull request by phenze**

### CODE REVIEW

**Comment by CRLgitrep** [comment]
Hi, I've tested existing API endpoints and found some to be still working. Thought I'd share, maybe it helps:

* v4/leagues/selection
* v4/leagues/[leagueId]/overview
* v4/leagues/[leagueId]/squad
* v4/leagues/[leagueId]/market
* v4/leagues/[leagueId]/me
* v4/leagues/[leagueId]/scoutedPlayers
* v4/leagues/[leagueId]/players/[playerId]
* v4/user/settings
* v4/user/targets (exists, i.e. no 404, but I couldn't use it)
* v4/notifications?leagueId=[leagueId]
* v4/competitions/[competitionId]/table (e.g. 1 = Bundesliga)

If anyone has more, please share, too, would be greatly appreciated!
I'll keep testing and update if I find any more endpoints.

**Comment by casudo** [comment]
> > Hi, I've tested existing API endpoints and found some to be still working. Thought I'd share, maybe it helps:
> 
> > 
> 
> > * v4/leagues/selection
> 
> > * v4/leagues/[leagueId]/overview
> 
> > * v4/leagues/[leagueId]/squad
> 
> > * v4/leagues/[leagueId]/market
> 
> > * v4/leagues/[leagueId]/me
> 
> > * v4/leagues/[leagueId]/scoutedPlayers
> 
> > * v4/leagues/[leagueId]/players/[playerId]
> 
> > * v4/user/settings
> 
> > * v4/user/targets (exists, i.e. no 404, but I couldn't use it)
> 
> > * v4/notifications?leagueId=[leagueId]
> 
> > * v4/competitions/[competitionId]/table (e.g. 1 = Bundesliga)
> 
> > 
> 
> > If anyone has more, please share, too, would be greatly appreciated! I'll keep testing and update if I find any more endpoints.
> 
> 
> 
> I have found those. I still did not figure out how to switch between matchdays when ```/v4/leagues/<leagueId>/ranking``` is definitly the ranking tab inside a league and you want to see specific stats from a matchday. I think that they changed it to be a query param? But i tried a lot like "d, matchDay, matchday, md, mdn" and it did not work..
> 
> ```
> 
> /v4/leagues/<leagueId>/managers/<userId>/squad
> 
> /v4/leagues/<leagueId>/ranking 
> 
> /v4/competitions/<competitionId>/matchdays 
> 
> /v4/competitions/<competitionId>/players
> 
> /v4/competitions/<competitionId>/players/<playerId> 
> 
> /v4/live/eventtypes
> 
> /v4/leagues/<leagueId>/teamcenter/myeleven
> 
> v4/base/overview
> 
> v4/bonus/collect
> 
> v4/leagues/list
> 
> v4/leagues/selection
> 
> v4/live/eventtypes
> 
> ```

I'll be taking a look at this once I have time. It's indeed a query paraneter, but I dont know which exact one it is right new.

**Comment by casudo** [comment]
@simonsagstetter It's `?dayNumber=x`

`https://api.kickbase.com/v4/leagues/{league_id}/ranking?dayNumber=9`

**Comment by simonsagstetter** [comment]
> @simonsagstetter It's `?dayNumber=x`
> 
> `https://api.kickbase.com/v4/leagues/{league_id}/ranking?dayNumber=9`

Thanks a lot! 

I feels quite difficult to find new ones because I think its the first time with v4 that they not only changed the app structure completely but also took care of the api and straighten it up. There still some views in the app I cannot find a related api endpoint. If someone does find the following I would be happy if you could share them:

`/v4/leagues/{league_id}/ranking?dayNumber=9` comes with a array "lp" which contains playerIds probably means leaguePlayers and i think some how you can work with `v4/leagues/{leagueId}/players/{playerId}/` and maybe a query param or additional endpoint to receive their whole performance like goals, cards, playtime etc. There is also this enpoint `/v4/competitions/{leagueId}/players/{playerId}` and I dont know whats the real diff between them.

I also couldnt find an endpoint to view the team player performance of a team when clicking on a team in competition>fixtures tab. `/v4/competitions/{competitionId}/matchdays` are all fixtures but I dont how the detail view works. Same goes for clicking into detail view when on competitions>leaderboard view `/v4/competitions/{competitionId}/table`

**Comment by casudo** [comment]
> `/v4/leagues/{league_id}/ranking?dayNumber=9` comes with a array "lp" which contains playerIds probably means leaguePlayers and i think some how you can work with `v4/leagues/{leagueId}/players/{playerId}/` and maybe a query param or additional endpoint to receive their whole performance like goals, cards, playtime etc. There is also this enpoint `/v4/competitions/{leagueId}/players/{playerId}` and I dont know whats the real diff between them.

The array "lp" stands for "Lined-up players" and are the players the user has lined up for that match day.

In terms of Player statistics, there a the following endpoints:
- Player Overview (`https://api.kickbase.com/v4/competitions/1/players/{player_id}?leagueId={league_id}`)
- Player Performance (`https://api.kickbase.com/v4/competitions/1/players/{player_id}/performance?leagueId={league_id}`)
- Player Market Value (`https://api.kickbase.com/v4/competitions/1/players/{player_id}/marketValue?leagueId={league_id}`)
- Player Transfer History (`https://api.kickbase.com/v4/leagues/{league_id}/players/{player_id}/transferHistory?start=0`)

Send a GET requests to the endpoints above and you'll see the difference if the name couldn't tell. :)

**Comment by CRLgitrep** [comment]
Thank you so much, I'm really stumped when it comes to finding all the endpoints.
@simonsagstetter: The live performance points used to be accessible at
* v2/leagues/{league_id}/livetable
But the endpoint was renamed for v4.

The marketValues endpoint is not working for me, (Status 404)

**Comment by simonsagstetter** [comment]
> Thank you so much, I'm really stumped when it comes to finding all the endpoints. @simonsagstetter: The live performance points used to be accessible at
> 
> * v2/leagues/{league_id}/livetable
>   But the endpoint was renamed for v4.
> 
> The marketValues endpoint is not working for me, (Status 404)

I think there is no need for a livetable endpoint as the ranking endpoint `v4/leagues/{leagueId}/ranking` without the query param `{dayNumber}` returns the latest matchday which is live when the first match started. I think internally you can check the status of a day from the properties "ia" and "il".

```
{...
     "day": 10, // current matchday or matchday from query param {dayNumber}
    "shmdn": 17,
    "sn": "24/25",
    "il": true, // isLive
    "nd": 34,
    "lfmd": 1,
    "ia": true // isAvailable
}
```

**Comment by phenze** [comment]
Would be great if we can update the postman collection here with the new endpoints

https://github.com/kevinskyba/kickbase-api-doc

**Comment by simonsagstetter** [comment]
> Would be great if we can update the postman collection here with the new endpoints
> 
> https://github.com/kevinskyba/kickbase-api-doc

I don't know if that respository is still maintained but I can share my postman collection when Im finished. Still missing some endpoints for player event and match event history. And the endpoint for match detail view when you click on a specific match in the competition fixtures view. I tried something like `v4/competitions/{competitionId}/matches/{matchId}/...` but it seems to be a dead end....

**Comment by casudo** [comment]
@simonsagstetter Images such as profile pictures moved from the API to their CDN.

**Comment by casudo** [comment]
@simonsagstetter Take a look at this: https://github.com/casudo/Kickbase-Insights/commit/3de5957597c1f1f4cce8d16b96901a9a7521eb94

You can see the URL for the profile picture there.

**Comment by simonsagstetter** [comment]
I have found a lot of new endpoints today and added my complete postman documentation + markdown file to my repository [Kickbase API v4 Docs](https://github.com/simonsagstetter/kickbase-api-v4-docs). I hope I can help with that

**Comment by casudo** [comment]
> > @CRLgitrep My bad, updated the Market Value endpoint above.
> 
> besides the /92 endpoint (3mo), there is at least one more working endpoint to get market values for the past year: [https://api.kickbase.com/v4/competitions/1/players/{player_id}/marketValue/365](https://api.kickbase.com/v4/competitions/1/players/%7Bplayer_id%7D/marketValue/365)
> 
> (I found both working for me without the league_id parameter)

Thanks for this finding! Makes sense, in the app you can toggle between 3 months and 1 year, but I didnt bother checking that...
This helps me a lot to re-implement the turnovers table for players which were assigned at start in Kickbase Insights!

**Comment by simonsagstetter** [comment]
> > @CRLgitrep My bad, updated the Market Value endpoint above.
> 
> besides the /92 endpoint (3mo), there is at least one more working endpoint to get market values for the past year: [https://api.kickbase.com/v4/competitions/1/players/{player_id}/marketValue/365](https://api.kickbase.com/v4/competitions/1/players/%7Bplayer_id%7D/marketValue/365)
> 
> (I found both working for me without the league_id parameter)

Yes thats right. Beacause this endpoints expects a parameter `{timeframe}`which can be 3 months or 1 year. Maybe there will be more in future releases. 

` /v4/competitions/{competitionId}/players/{player_id}/marketvalue/{timeframe}`
or
` /v4/leagues/{leagueId}/players/{player_id}/marketvalue/{timeframe}`

**Pull request merged**
